### ISSUE TITLE
can't load libEDK

### ISSUE THREAD

**Issue by zainabhn** [Emotiv/community-sdk#100]
Hey!
I'm using the EPOC+ headset and want to connect it to my Raspberry Pi (Raspbian).
I'm trying to simple run the EEGlogger python code but it fails with the message "Cannot load dll lib"
and NameError: name 'libEDK not defined"

Any suggestions on how to fix this issue?
PS. The libEDK.so file is placed in the same dir as the .py and I've made sure the library path is okay

**Comment by hoangphamemotiv** [comment]
Hi zainabhn
In .py file, you try to replace 
    libPath = srcDir + "/../../bin/armhf/libedk.so"
with 
    libPath = "./libedk.so"

**Comment by zainabhn** [comment]
I tried that
It doesn't help :\

Just for reference,this is the code:
try :
    if sys.platform.startswith('win32'):     
        #libEDK = cdll.LoadLibrary("edk.dll")
        print "Windows" 
    if sys.platform.startswith('linux'):
        srcDir = os.getcwd()    
        libPath = srcDir+"/libedk.so"
        libEDK = CDLL("./libedk.so")
except :
    print 'Error : cannot load dll lib' 


and this is the error:
Error : cannot load dll lib
Traceback (most recent call last):
  File "eeg_logger.py", line 46, in <module>
    eEvent      = libEDK.IEE_EmoEngineEventCreate()
NameError: name 'libEDK' is not defined

**Comment by havietnam** [comment]
Please clone and try again.
I fixed armhf soft link.
P/S: Correct code for load library is:
**libEDK = CDLL(libPath)**

**Comment by zainabhn** [comment]
thanks for the reponse havietnam
However, I'm still not able to compile the example
Just to make sure, here's what I'm doing

I've copied the edk files from bin/armhf into the folder containing the python example.
Then using the command line, I give the following command:

python eeg_logger.py 

it gives me an error saying "can not load dll file" and
libEDK not defined.

I'm sure I'm doing something really stupid and wrong.
Can you please help?

I have this project due in 2 days! :S

**Comment by havietnam** [comment]
If you not sure, please using full path name to libedk.so.3.3.2. For Ex:libEDK = CDLL("/home/yourname/libedk.so.3.3.2")

**Comment by federicotejada** [comment]
I got the same problem, did you solve it?
