### ISSUE TITLE
Load training profile

### ISSUE THREAD

**Issue by Shahad56** [Emotiv/community-sdk#269]
I'm trying to train my mental commands with Emotiv Xavier then upload the training profile to the cloud, then load that profile to MentalCommandWithCloudProfile.py . whenever I type "load_profile" I always get "load failed".
What shall I do to load the trained profile to my code?

**Comment by tungntEmotiv** [comment]
Hi @Shahad56 
You received "upload successfully" from Control Panel , dint you ? . If yes, you can load your profile by call LoadUserProfile() api similar to https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/SavingAndLoadingProfileCloud.py.

**Comment by Shahad56** [comment]
yes, I did. I trained "push" and got skill rating of "47%". When I run SavingAndLoadingProfileCloud.py.  and press "2" for loading profile from the cloud, I get "loading finished. But when I run MentalCommandWithCloudProfile.py , I always get "loading failed"!
How can I fix this??

**Comment by Shahad56** [comment]
HELP guys!!!!

**Comment by tungntEmotiv** [comment]
Hi @Shahad56

Thank you for raising the issue. We found a mistake issue in MentalCommandWithCloudProfile.py, wrong user ID used in load_profile. We have corrected and upload to git. Please pull the latest.
We really sorry because of the mistake
Regards

**Comment by Shahad56** [comment]
The same problem still appears, I train with control panel the press "Upload Profile", I get "upload successful". When I run the code I type "load profile" I get "load finished". And the type "report", all I get is zeros for all mental commands while my push skills in control panel is 43%.
What shall I do??

**Comment by tungntEmotiv** [comment]
Hi @Shahad56 

We have fixed this issue on develop branch (is going to merge with master in few days). Please get the example for your development. The issue occurred in case report of the example.  
https://github.com/Emotiv/community-sdk/tree/develop/examples_basic/Python 
Please get the utilities.py file also . We have defined some Enum in the utilities file.
Thank for your raising the issue. Please let me known the result.

**Comment by Shahad56** [comment]
I'm executing the code with Python2.7 and it keeps showing error "ImportError: No module named enum", but when I excute with python  3.6 I get ride of this issue but I get " cannot connect to emotiv cloud". I'm pretty sure I'm logged in. What shall I do now please?

**Comment by duytan90** [comment]
Hi @Shahad56, please install module enum34 on Python 2.7 to work with enum type
```
pip install enum34
```
and use Python 2.7 instead of Python 3.4

**Comment by Shahad56** [comment]
Thank you so much, that really helped on Windows 7.
Now I need to run the code on my Rpi3 running Ubuntu. When I run it I get "Cannot connect to emotiv cloud". I made sure that I put the right user name and password in the code, and that I logged in on emotiv site.
How can I fix this now??

**Comment by duytan90** [comment]
Hi @Shahad56, on Windows, Python examples loaded edk.dll which is Emotiv SDK v3.5.
On Linux/RP3, Python examples load the libedk.so library, which is Emotiv SDK v3.3.x and doesn't have Cloud APIs. So you can only run [basic_example](https://github.com/Emotiv/community-sdk/tree/master/examples_basic) for now.

**Comment by duytan90** [comment]
I don't know about releasing process, but I think it will be available soon.

**Comment by Shahad56** [comment]
I know I asked too much, now I just need to know if I installed Windows on raspberry, shall I use edk.dll or libedk.so??
thank you

**Comment by hoangphamemotiv** [comment]
Hi @Shahad56 

current SDK version, we dont support Windows on raspberry.
